### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by NickLewry** [NickLewry/bleet#5]
- [ ] Tests for AppContent
- [ ] Populate feed with stories
- [ ] Responsive design
- [ ] Add more user specific data, ie location, etc
- [ ] Overall styling
